name: login_page
description: "The Official App of C-Cell LNMIIT"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+5

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  animated_bottom_navigation_bar: ^1.4.0
  http: ^1.4.0
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  salomon_bottom_bar: ^3.3.2
  fluid_background: ^1.0.5
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  web: any
  js: ^0.7.2
  pwa_install: ^0.0.6
  uuid: ^4.5.1
  provider: ^6.0.5  # Added for theme management

#  flutter_url_strategy: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  animated_icon: ^0.0.9
  file_picker: ^10.2.0
  image_picker_for_web: ^3.0.6
  flutter_screenutil: ^5.9.3
  syncfusion_flutter_pdfviewer: ^30.1.41
  dio: ^5.8.0+1
  permission_handler: ^12.0.1
  animated_toggle_switch: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ccell_logo_c.png"

flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/images/ccell_logo_c.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/ccell_logo.png
      - assets/hostel.png
      - assets/document.png
      - assets/biometric.png
      - assets/antirag.png
      - assets/credential.png
      - assets/welcome_illustration.png
      - assets/images/ccell_logo_c.png
      - assets/images/Frame.png
      - assets/images/google_logo.png
      - assets/images/academic_calender.png
      - assets/images/bus_timetable.png
      - assets/images/find_location.png
      - assets/images/lost_found.png
      - assets/images/mess_menu.png
      - assets/images/profile.png
      - assets/images/Frame_dark.png
      - assets/images/ccell_logo_dark.png
      - assets/images/loading_screen.png
      - assets/images/y24.jpg
      - assets/images/gmail.png
      - assets/images/phone_icon.png
      - assets/images/usha_mam.jpg
      - assets/images/arpit_joshi.jpg
      - assets/images/Harshita.jpg
      - assets/images/naman.jpg
      - assets/images/atharv_shah.jpg
      - assets/images/kunal_sharma.png
      - assets/images/nikhila.jpg
      - assets/images/ishita.jpg
      - assets/images/praneel.jpg
      - assets/images/armaan.png
      - assets/images/panth_moradiya.jpg
      - assets/images/yash_raj.jpg
      - assets/images/neha_raniwala.jpg
      - assets/images/vibha_gupta.jpg
      - assets/images/mudit_img.jpg
      - assets/images/aditya_kansal.webp
      - assets/images/rahul_sharma.jpg
      - assets/images/lakshita.jpeg
      - assets/images/Instagram.png
      - assets/images/tech/cipherclub/cipher_logo.png
      - assets/images/tech/phoenix/phoenix_logo.png
      - assets/images/tech/quizzinga/quizzinga_logo.jpg
      - assets/images/sports/badminton/badminton_logo.jpeg
      - assets/images/sports/basketball/basketball_logo.png
      - assets/images/sports/cricket/cricket_logo.jpeg
      - assets/images/sports/football/football_logo.jpg
      - assets/images/sports/kabaddi/kabaddi_logo.jpeg
      - assets/images/sports/lawn_tennis/lawnt_logo.png
      - assets/images/sports/table_tennis/tablet_logo.png
      - assets/images/cultural/aaveg/aaveg_logo.png
      - assets/images/cultural/capriccio/capriccio_logo.jpg
      - assets/images/cultural/eminence/eminence_logo.jpg
      - assets/images/cultural/imagination/imagi_logo.jpg
      - assets/images/cultural/insignia/insignia_logo.jpg
      - assets/images/cultural/lc/lc_logo.jpg
      - assets/images/cultural/mediacell/media_logo.jpg
      - assets/images/cultural/rendition/rendition_logo.png
      - assets/images/cultural/sankalp/sankalp_logo.jpg
      - assets/images/cultural/vignette/vignette_logo.jpg
      - assets/images/sports/squash/squash_logo.jpeg
      - assets/images/sports/chess/chess_logo.jpg
      - assets/images/cultural/fundoo/fundoo_logo.jpg
      - assets/images/sports/volleyball/volleyball_logo.jpg
      - assets/images/plinth/plinth_logo.jpg
      - assets/images/despo/despo_logo.jpeg
      - assets/images/viva/viva_logo.png
      - assets/images/ted_logo.jpg
      - assets/images/esummit/esummit_logo.jpg
      - assets/images/cosha_logo.jpg
      - assets/images/youtube_logo.png
      - assets/images/tech/cybros/cybros_logo.jpg
      - assets/images/tech_logo.jpg
      - assets/images/sports_logo.jpg
      - assets/images/linkedin_logo.png
      - assets/images/facebook.png
      - assets/images/x.png
      - assets/pages/faces/
      - assets/images/tech/debsoc/debsoc_logo.jpg
      - assets/images/tech/astronomy/astro_logo.jpg
      - assets/images/tech/ecell/ecell_logo.jpg
      - assets/images/comingsoon.png
      - assets/images/campus map.jpg
      - assets/images/cult_logo.jpeg
      - assets/images/ccell_logo_dark_border.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
