    // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'core/config/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu41rfJeJKIQngNDthdZT5SwAxNEtxHOU',
    appId: '1:655780948496:web:6b30f127ca19d672453895',
    messagingSenderId: '655780948496',
    projectId: 'ccell-b8c42',
    authDomain: 'ccell-b8c42.firebaseapp.com',
    databaseURL: 'https://ccell-b8c42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccell-b8c42.firebasestorage.app',
    measurementId: 'G-KPM10BTRWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZvq01FIpK62QE9OCovHyz_eOsY7ctwaE',
    appId: '1:655780948496:android:d56cead95d5ee4c8453895',
    messagingSenderId: '655780948496',
    projectId: 'ccell-b8c42',
    databaseURL: 'https://ccell-b8c42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccell-b8c42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt3vJmJsCWrC_IHhtE9YboXaiM4FHILmA',
    appId: '1:655780948496:ios:7ebb110123776616453895',
    messagingSenderId: '655780948496',
    projectId: 'ccell-b8c42',
    databaseURL: 'https://ccell-b8c42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccell-b8c42.firebasestorage.app',
    androidClientId: '655780948496-02h6tn5tvophecsc1n67t7q2dqsvntsd.apps.googleusercontent.com',
    iosClientId: '655780948496-bqmn6dtahm162ul19u6bie4ogstd99ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt3vJmJsCWrC_IHhtE9YboXaiM4FHILmA',
    appId: '1:655780948496:ios:7ebb110123776616453895',
    messagingSenderId: '655780948496',
    projectId: 'ccell-b8c42',
    databaseURL: 'https://ccell-b8c42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccell-b8c42.firebasestorage.app',
    androidClientId: '655780948496-02h6tn5tvophecsc1n67t7q2dqsvntsd.apps.googleusercontent.com',
    iosClientId: '655780948496-bqmn6dtahm162ul19u6bie4ogstd99ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu41rfJeJKIQngNDthdZT5SwAxNEtxHOU',
    appId: '1:655780948496:web:598dca94366f65f4453895',
    messagingSenderId: '655780948496',
    projectId: 'ccell-b8c42',
    authDomain: 'ccell-b8c42.firebaseapp.com',
    databaseURL: 'https://ccell-b8c42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ccell-b8c42.firebasestorage.app',
    measurementId: 'G-8BCR065BXF',
  );

}